[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmd = "python3.10 -m pip install --upgrade pip && python3.10 -m pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 server:app"
