[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["python"]

[build.nixpacks.config]
pythonVersion = "3.10.12"

[build.nixpacks.env]
PYTHONPATH = "/app"
OPENCV_VIDEOIO_PRIORITY_MSMF = "0"
PIP_NO_CACHE_DIR = "1"
SETUPTOOLS_USE_DISTUTILS = "stdlib"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --worker-class sync --max-requests 1000 --max-requests-jitter 100 server:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10